### ISSUE TITLE
dz4

### ISSUE THREAD

**Issue by Sofya112** [MIEE-ACS/domashnee-zadanie-no4-Sofya112#1]
готово

**Comment by d-makarenko** [comment]
Хорошо, одно замечание: в задании было написано:

Данная работа включает в себя два задания: на одномерные массивы и на двумерные. Для каждого задания должен быть создан отдельный проект, при этом оба проекта должны находиться в одном решении (Solution)

Прошу в следующий раз выполнять так, как было указано, это сильно облегчает проверку.
